FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    default-jdk \
    g++ \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

RUN python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["bash", "-c", "python manage.py migrate && gunicorn time_complexity_analyzer.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 300"]
